[project]
name = "mcputils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.52.0",
    "fastmcp>=2.5.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.1",
    "python-dotenv>=1.1.0",
]
